all:
  hosts:
    server:
      ansible_host: 192.168.11.102
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/server/virtualbox/private_key
servers:
  hosts:
    server: